import pandas as pd
import streamlit as st

st.set_page_config(
    page_title="Support KPI AI Portal", layout="wide", page_icon="📊"
)
st.title("📊 Customer Support KPI & AI Analytics Portal")

# ---------------------------------------------------------------- config

KPI_CONFIGS = [
    {
        "label": "Total Ticket Volume",
        "col": "ticket_id",
        "agg": "count",
        "higher_is_better": False,
        "decimals": 0,
        "advice": "review staffing and deflection (FAQ, self-service).",
    },
    {
        "label": "Avg CSAT Score",
        "col": "csat_score",
        "agg": "mean",
        "higher_is_better": True,
        "decimals": 2,
        "advice": "sample low-scoring tickets for recurring themes.",
    },
    {
        "label": "Avg Handle Time (sec)",
        "col": "total_aht_duration_seconds",
        "agg": "mean",
        "higher_is_better": False,
        "decimals": 1,
        "advice": "check for knowledge-base gaps or tooling slowdowns.",
    },
    {
        "label": "Avg Wait Time (sec)",
        "col": "wait_time",
        "agg": "mean",
        "higher_is_better": False,
        "decimals": 1,
        "advice": "review queue coverage during peak hours.",
    },
]

CHART_COLUMNS = {
    "ticket_id": ("Daily Tickets", "count"),
    "csat_score": ("CSAT Score", "mean"),
    "total_aht_duration_seconds": ("Avg Handle Time (s)", "mean"),
    "wait_time": ("Avg Wait Time (s)", "mean"),
}

DAYS_MAP = {"Last Week": 7, "Last Month": 30, "Last 3 Months": 90}
SIGNIFICANCE_THRESHOLD = 2.0

# ---------------------------------------------------------------- helpers


def aggregate(frame, kpi):
    """Single value for one KPI over one slice. NaN if unavailable."""
    if kpi["agg"] == "count":
        return float(len(frame))
    if kpi["col"] not in frame.columns or frame.empty:
        return float("nan")
    return frame[kpi["col"]].mean()


def pct_delta(current, previous):
    """Percentage change, or None when there is no valid baseline."""
    if pd.isna(current) or pd.isna(previous) or previous == 0:
        return None
    return ((current - previous) / previous) * 100.0


def format_value(value, decimals):
    if pd.isna(value):
        return "n/a"
    return f"{value:,.{decimals}f}"


def classify(kpi, change):
    """Return (status, sentence) for one KPI."""
    label = kpi["label"]
    if change is None:
        return "neutral", (
            f"**No baseline ({label}):** the previous period contains no "
            f"comparable records, so no trend can be calculated."
        )
    if abs(change) < SIGNIFICANCE_THRESHOLD:
        return "neutral", (
            f"**Stable ({label}):** movement of {change:+.1f}% versus the "
            f"previous period — within normal variation."
        )
    improved = (change > 0) if kpi["higher_is_better"] else (change < 0)
    if improved:
        return "good", (
            f"**Improving ({label}):** {change:+.1f}% versus the previous "
            f"period. Worth identifying what changed so it can be repeated."
        )
    return "bad", (
        f"**Needs attention ({label}):** {change:+.1f}% versus the previous "
        f"period — {kpi['advice']}"
    )


def build_report(company, timeframe, period, rows):
    """Plain-text summary suitable for pasting into an email."""
    current_start, current_end, previous_start, previous_end = period
    lines = [
        f"# Support KPI Summary — {company}",
        "",
        f"Timeframe: {timeframe}",
        f"Current period:  {current_start:%Y-%m-%d} to {current_end:%Y-%m-%d}",
        f"Previous period: {previous_start:%Y-%m-%d} to {previous_end:%Y-%m-%d}",
        "",
        "## Metrics",
        "",
        "| Metric | Current | Previous | Change |",
        "| --- | ---: | ---: | ---: |",
    ]
    for row in rows:
        change = (
            f"{row['change']:+.1f}%" if row["change"] is not None else "n/a"
        )
        lines.append(
            f"| {row['label']} | {row['current_str']} | "
            f"{row['previous_str']} | {change} |"
        )

    lines += ["", "## Observations", ""]
    for row in rows:
        lines.append(f"- {row['sentence'].replace('**', '')}")

    lines += [
        "",
        "---",
        "Generated by the Support KPI Portal. Figures are unweighted means "
        "over the selected window.",
    ]
    return "\n".join(lines)


def slugify(text):
    keep = [c if c.isalnum() else "-" for c in str(text).lower()]
    return "".join(keep).strip("-").replace("--", "-") or "export"


# ---------------------------------------------------------------- input

uploaded_file = st.file_uploader("Upload raw CSV dataset", type=["csv"])

if uploaded_file is None:
    st.info(
        "Upload a CSV containing at least `date`, `company` and `ticket_id` "
        "columns to begin."
    )
    st.stop()

df = pd.read_csv(uploaded_file)

missing = [c for c in ("date", "company", "ticket_id") if c not in df.columns]
if missing:
    st.error(f"Missing required column(s): {', '.join(missing)}")
    st.stop()

df["date"] = pd.to_datetime(df["date"], errors="coerce")
unparsed = int(df["date"].isna().sum())
df = df.dropna(subset=["date"])

if df.empty:
    st.error("No rows with a valid date remain after parsing.")
    st.stop()

for col in (
    "csat_score",
    "total_aht_duration_seconds",
    "wait_time",
    "agent_speed_to_answer",
):
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# Normalising to midnight removes the partial-final-day problem.
df["_day"] = df["date"].dt.normalize()

if unparsed:
    st.warning(f"{unparsed:,} row(s) dropped — unreadable date values.")

# ---------------------------------------------------------------- filters

st.sidebar.header("Filter Options")
companies = sorted(df["company"].dropna().unique())
if not companies:
    st.error("No company values found in the dataset.")
    st.stop()

selected_company = st.sidebar.selectbox("Select Company", companies)
timeframe = st.sidebar.radio("Select Timeframe", list(DAYS_MAP))
days_count = DAYS_MAP[timeframe]

company_df = df[df["company"] == selected_company]
current_end = company_df["_day"].max()

# Inclusive windows of exactly `days_count` days each, back to back.
current_start = current_end - pd.Timedelta(days=days_count - 1)
previous_end = current_start - pd.Timedelta(days=1)
previous_start = previous_end - pd.Timedelta(days=days_count - 1)

current_df = company_df[
    (company_df["_day"] >= current_start) & (company_df["_day"] <= current_end)
]
previous_df = company_df[
    (company_df["_day"] >= previous_start)
    & (company_df["_day"] <= previous_end)
]

st.subheader(f"Dashboard for {selected_company}")
st.caption(
    f"{current_start:%Y-%m-%d} → {current_end:%Y-%m-%d} "
    f"({days_count} days), compared against "
    f"{previous_start:%Y-%m-%d} → {previous_end:%Y-%m-%d}"
)

if current_df.empty:
    st.warning("No records found for the selected timeframe.")
    st.stop()

if previous_df.empty:
    st.info(
        "The comparison window contains no data, so period-over-period "
        "changes are unavailable."
    )

# ---------------------------------------------------------------- compute

kpi_rows = []
for kpi in KPI_CONFIGS:
    current_value = aggregate(current_df, kpi)
    previous_value = aggregate(previous_df, kpi)
    change = pct_delta(current_value, previous_value)
    status, sentence = classify(kpi, change)
    kpi_rows.append(
        {
            "label": kpi["label"],
            "current": current_value,
            "previous": previous_value,
            "current_str": format_value(current_value, kpi["decimals"]),
            "previous_str": format_value(previous_value, kpi["decimals"]),
            "change": change,
            "status": status,
            "sentence": sentence,
            "higher_is_better": kpi["higher_is_better"],
        }
    )

# ---------------------------------------------------------------- cards

cols = st.columns(len(kpi_rows))
for column, row in zip(cols, kpi_rows):
    with column:
        st.metric(
            label=row["label"],
            value=row["current_str"],
            delta=(
                f"{row['change']:+.1f}%"
                if row["change"] is not None
                else None
            ),
            # Without this, a rise in handle time renders green.
            delta_color="normal" if row["higher_is_better"] else "inverse",
        )

st.divider()

# ---------------------------------------------------------------- charts

st.subheader("📈 Interactive Performance Trends")

available = {
    col: spec for col, spec in CHART_COLUMNS.items() if col in current_df.columns
}
daily_df = (
    current_df.groupby("_day")
    .agg(**{spec[0]: (col, spec[1]) for col, spec in available.items()})
    .sort_index()
)
daily_df.index.name = "Date"

tab1, tab2, tab3 = st.tabs(
    ["Ticket Volume", "CSAT Score Trend", "Handle & Wait Times"]
)


def draw(container, series_names):
    present = [name for name in series_names if name in daily_df.columns]
    with container:
        if present:
            st.line_chart(daily_df[present])
        else:
            st.caption("This metric is not present in the uploaded file.")


draw(tab1, ["Daily Tickets"])
draw(tab2, ["CSAT Score"])
draw(tab3, ["Avg Handle Time (s)", "Avg Wait Time (s)"])

st.divider()

# ---------------------------------------------------------------- insights

st.subheader("💡 Insights & Trend Highlights")

renderers = {"good": st.success, "bad": st.error, "neutral": st.info}
for row in kpi_rows:
    renderers[row["status"]](row["sentence"])

st.divider()

# ---------------------------------------------------------------- export

st.subheader("⬇️ Export")

period = (current_start, current_end, previous_start, previous_end)
report_text = build_report(selected_company, timeframe, period, kpi_rows)
stem = f"{slugify(selected_company)}-{slugify(timeframe)}-{current_end:%Y%m%d}"

export_df = current_df.drop(columns=["_day"])
summary_df = pd.DataFrame(
    [
        {
            "Metric": row["label"],
            "Current": row["current"],
            "Previous": row["previous"],
            "Change %": row["change"],
        }
        for row in kpi_rows
    ]
)

left, middle, right = st.columns(3)

with left:
    st.download_button(
        "Filtered rows (CSV)",
        data=export_df.to_csv(index=False).encode("utf-8"),
        file_name=f"{stem}-rows.csv",
        mime="text/csv",
        use_container_width=True,
        help=f"{len(export_df):,} rows currently in view.",
    )

with middle:
    st.download_button(
        "KPI summary (CSV)",
        data=summary_df.to_csv(index=False).encode("utf-8"),
        file_name=f"{stem}-summary.csv",
        mime="text/csv",
        use_container_width=True,
        help="One row per metric, with deltas.",
    )

with right:
    st.download_button(
        "Written report (Markdown)",
        data=report_text.encode("utf-8"),
        file_name=f"{stem}-report.md",
        mime="text/markdown",
        use_container_width=True,
        help="Narrative summary for forwarding on.",
    )

with st.expander("Preview the written report"):
    st.markdown(report_text)
